services:

  app:
    container_name: carrrent
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_DNS=postgres://postgres:postgres@db:5432/carrent?sslmode=disable
      - MIGRATE_PATH=migrations
    volumes:
      - ./migrations:/root/migrations
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=carrent
    ports:
      - 5432:5432